#ifndef __TACTICAL_ALL_H
#define __TACTICAL_ALL_H

#pragma message("GENERATED PCH FOR TACTICAL PROJECT.")

#include "sgp.h"
#include "air_raid.h"
#include "game_event_hook.h"
#include "game_clock.h"
#include "auto_bandage.h"
#include "strategic_map.h"
#include "screen_ids.h"
#include "ja_screens.h"
#include "random.h"
#include "overhead_types.h"
#include "sound_control.h"
#include "timer_control.h"
#include "dialogue_control.h"
#include "overhead.h"
#include "message.h"
#include "isometric_utils.h"
#include "soldier_macros.h"
#include "world_man.h"
#include "los.h"
#include "math.h"
#include "explosion_control.h"
#include "interface.h"
#include "music_control.h"
#include "campaign_types.h"
#include "game_settings.h"
#include "text.h"
#include "morale.h"
#include "map_screen_helicopter.h"
#include <stdio.h>
#include <string.h>
#include "types.h"
#include "wcheck.h"
#include <stdlib.h>
#include "animation_cache.h"
#include "animation_data.h"
#include "animation_control.h"
#include "sys_globals.h"
#include "debug_control.h"
#include "file_man.h"
#include "weapons.h"
#include "structure.h"
#include "world_def.h"
#include "rotting corpses.h"
#include "points.h"
#include "soldier_control.h"
#include "tile_def.h"
#include "utilities.h"
#include "arms_dealer_init.h"
#include "arms_dealer_inv_init.h"
#include "soldier_profile.h"
#include "handle_items.h"
#include "item_types.h"
#include "message_box_screen.h"
#include "handle_ui.h"
#include "items.h"
#include "merc_text_box.h"
#include "render_world.h"
#include "strategic_turns.h"
#include "event_pump.h"
#include "ai.h"
#include "interface_control.h"
#include "map_screen_interface.h"
#include "map_screen_interface_bottom.h"
#include "assignments.h"
#include "word_wrap.h"
#include "cursors.h"
#include "english.h"
#include "boxing.h"
#include "render_fun.h"
#include "npc.h"
#include "opplist.h"
#include <errno.h>
#include "vsurface.h"
#include "render_dirty.h"
#include "sysutil.h"
#include "container.h"
#include "video.h"
#include "vobject_blitters.h"
#include "faces.h"
#include "gap.h"
#include "bullets.h"
#include <wchar.h>
#include "mem_man.h"
#include "campaign.h"
#include "strategic_mines.h"
#include ""strategic_status.h"
#include "encrypted_file.h"
#include "mercs.h"
#include "interface dialogue.h"
#include "squads.h"
#include "interface_utils.h"
#include "quests.h"
#include "game_screen.h"
#include "shopkeeper_interface.h"
#include "merc_contract.h"
#include "history.h"
#include "town_militia.h"
#include "meanwhile.h"
#include "skill_check.h"
#include "finances.h"
#include "drugs and alcohol.h"
#include "teamturns.h"
#include "font_control.h"
#include "line.h"
#include "structure wrap.h"
#include "pathai.h"
#include "smell.h"
#include "fov.h"
#include "keys.h"
#include "input.h"
#include "exit grids.h"
#include "environment.h"
#include "fog_of_war.h"
#include "sound_man.h"
#include <stdarg.h>
#include <time.h>
#include "tile animation.h"
#include "interactive_tiles.h"
#include "handle doors.h"
#include "action_items.h"
#include "World items.h"
#include "interface items.h"
#include "physics.h"
#include "interface panels.h"
#include "strategic_town_loyalty.h"
#include "soldier functions.h"
#include "save_load_map.h"
#include "soldier add.h"
#include "soldier ani.h"
#include "qarray.h"
#include "handle_ui_plan.h"
#include "soldier_create.h"
#include "mouse_system.h"
#include "cursor control.h"
#include "interface cursors.h"
#include "UI cursors.h"
#include "strategic_pathing.h"
#include "strategic movement.h"
#include "strategic.h"
#include "vehicles.h"
#include "game_loop.h"
#include "image.h"
#include "vobject.h"
#include "button_system.h"
#include "radar screen.h"
#include "lighting.h"
#include "strategic_exit_gui.h"
#include "popup_box.h"
#include "spread burst.h"
#include "tactical_save.h"
#include "fade_screen.h"
#include "strategic_ai.h"
#include "map_screen.h"
#include "laptop_save.h"
#include "map_screen_interface_map.h"
#include "map_screen_interface_map_inventory.h"
#include "overhead_map.h"
#include "options_screen.h"
#include <memory.h>
#include "inventory_choosing.h"
#include "smoothing_utils.h"
#include "tile_dat.h"
#include <math.h>
#include "phys_math.h"
#include "map_information.h"
#include "soldier_init_list.h"
#include "editor_mercs.h"
#include "ja2.h"
#include "road_smoothing.h"
#include "tile cache.h"
#include "merc_entering.h"
#include "merc_hiring.h"
#include "strategic_merc_handler.h"
#include "militia_control.h"
#include "queen_command.h"
#include "edit_screen.h"  
#include "soldier_tile.h"
#ifdef  NETWORKED
	#include "Networking.h"
	#include "NetworkEvent.h"
#endif
#include "player_command.h"
#include "game_init.h"
#include "buildings.h"
#include "rt_time_defines.h"
#include	"game_settings.h"
#include "text_input.h"
#include "shopkeeper_quotes.h"
#include "personnel.h"
#include "pits.h"
#include "smokeeffects.h"
#include "save_load_game.h"
#include "scheduling.h"
#include "auto_resolve.h"
#include "soldier find.h"
#include "aim.h"
#include "strategic_town_reputation.h"
#include "tactical_turns.h"
#include "lighteffects.h"
#include "soldier_profile_type.h"
#include "ai_list.h"
#include "quest_debug.h"
#include "game_events.h"
#include "bobby_ray.h"

#include "enemy_item_drops.h"

#ifdef JA2BETAVERSION
	#include	"quest_debug_system.h"
#endif

#include "game_version.h"
#include "save_load_screen.h"
#include "cheats.h"
#include "animated_progressbar.h"
#include "civ quotes.h"
#include "aim_members.h"
#include "bobby_ray_mail_order.h"
#include "end game.h"
#include "display_cover.h"
#include "expat.h"
#include "spread burst.h"
#include "xml.h"

#endif