#include "BuildDefines.h"

#ifndef __EDITOR_ALL_H
#define __EDITOR_ALL_H

#ifdef JA2EDITOR

#pragma message("GENERATED PCH FOR EDITOR PROJECT.")

//external
#include "types.h"
#include <stdio.h>
#include "action_items.h"
#include "button_system.h"
#include "debug.h"
#include "english.h"
#include "environment.h"
#include "exit_grids.h"
#include "font.h"
#include "font_control.h"
#include "keys.h"
#include "input.h"
#include "interface.h"
#include "interface_items.h"
#include "isometric_utils.h"
#include "interface panels.h"
#include "lighting.h"
#include "map_information.h"
#include "mouse_system.h"
#include "overhead.h"
#include "Overhead map.h"
#include "overhead types.h"
#include "pits.h"
#include "random.h"
#include "render_fun.h"
#include "render_dirty.h"
#include "render_world.h"
#include "simple_render_utils.h"
#include "soldier_create.h"
#include "soldier_find.h"
#include "sysutil.h"
#include "text.h"
#include "text_input.h"
#include "tile_def.h"
#include "utilities.h"
#include "video.h"
#include "vobject.h"
#include "vobject_blitters.h"
#include "vsurface.h"
#include "wcheck.h"
#include "weapons.h"
#include "wordwrap.h"
#include "world_dat.h"
#include "world_def.h"
#include "world_items.h"
#include "world_man.h"
#include "line.h"
#include "animation_data.h"
#include "animation_control.h"
#include "soldier_init_list.h"
#include "StrategicMap.h"
#include "soldier_add.h"
#include "soldier_control.h"
#include "soldier_profile_type.h"
#include "soldier_profile.h"
#include "inventory_choosing.h"
#include "scheduling.h"
#include "timer_control.h"
#include "sgp.h"
#include "screen_ids.h"
#include "sys_globals.h"
#include "interactive_tiles.h"
#include "handle_ui.h"
#include "event_pump.h"
#include "message.h"
#include "game_clock.h"
#include "game_init.h"
#include "map_edgepoints.h"
#include "music_control.h"
#include <memory.h>
#include "item_types.h"
#include "items.h"
#include "handle_items.h"
#include "animated_progressbar.h"
#include "game_loop.h"
#include <stdlib.h>
#include "structure_internals.h"
#include "cursors.h"
#include "file_man.h"
#include "summary_info.h"
#include "time.h"
#include "structure wrap.h"
#include "message_box_screen.h"
#include "game_settings.h"


//internal
#include "cursor_modes.h"
#include "edit_sys.h"
#include "editor_callback_prototypes.h"
#include "editor_modes.h"
#include "editor_taskbar_creation.h"
#include "editor_taskbar_utils.h"
#include "editor_undo.h"
#include "editor_buildings.h"
#include "editor_defines.h"
#include "editor_items.h"
#include "editor_map_info.h"
#include "editor_mercs.h"
#include "editor_terrain.h"
#include "edit_screen.h"
#include "item_statistics.h"
#include "load_screen.h"
#include "messagebox.h"
#include "new_smooth.h"
#include "popup_menu.h"
#include "road_smoothing.h"
#include "sector_summary.h"
#include "select_win.h"
#include "smart_method.h"
#include "smooth.h"
#include "smoothing_utils.h"

#endif

#endif
