#ifndef __AI_ALL_H
#define __AI_ALL_H

#pragma message("GENERATED PCH FOR TACTICAL AI PROJECT.")

#include "ai_list.h"
#include "overhead.h"
#include "debug.h"
#include "ai_internals.h"
#include "wcheck.h"
#include "sgp.h"
#include "ai.h"
#include "isometric_utils.h"
#include "math.h"
#include "event_pump.h"
#include "overhead_types.h"
#include "sys globals.h"
#include "opplist.h"
#include "animation control.h"
#include "font control.h"
#include "interface.h"
#include "screen_ids.h"
#include "world_man.h"
#include "path_ai.h"
#include "points.h"
#include "weapons.h"
#include "items.h"
#include "handle_items.h"
#include "animation data.h"
#include "los.h"
#include "message.h"
#include "team_turns.h"
#include "npc.h"
#include "dialogue_control.h"
#include "soldier_profile.h"
#include "strategic_map.h"
#include "tactical_save.h"
#include "soldier_create.h"
#include "explosion_control.h"
#include "interactive_tiles.h"
#include "interface dialogue.h"
#include "vehicles.h"
#include "render_world.h"
#include "assignments.h"
#include "soldier_functions.h"
#include "game_settings.h"
#include "buildings.h"
#include "Physics.h"
#include "bullets.h"
#include "Spread Burst.h"
#include "skill_check.h"
#include "types.h"
#include "soldier control.h"
#include "rotting_corpses.h"
#include "soldier add.h"
#include "scheduling.h"
#include "structure_wrap.h"
#include "keys.h"
#include "render_fun.h"
#include "boxing.h"
#include <stdlib.h>
#include "world_items.h"
#include "map_edgepoints.h"
#include "text.h"
#include "video.h"
#include "smell.h"
#include "map_screen.h"
#include "strategic.h"
#include "strategic_pathing.h"
#include "quests.h"
#include "game_clock.h"
#include "file_man.h"
#include "Random.h"
#include "QuestDEBUG.H"
#include "soldier_macros.h"
#include "strategic_town_loyalty.h"
#include "timer_control.h"
#include "Soldier Tile.h"
#include "meanwhile.h"
#include "campaign_types.h"
#ifdef JA2TESTVERSION
	#include	"quest_debug_system.h"
	#include	"quest_text.h"
#endif

#include "stdarg.h"
#include <stdio.h>
#include "Soldier Profile Type.h"
#include "finances.h"
#include "civ_quotes.h"
#include "arms_dealer_init.h"
#include "interface_panels.h"
#include "soldier_ani.h"
#include "queen_command.h"
#include "Lighting.h"
#include "environment.h"
#include "sound_control.h"

#endif