#ifndef __JA2_ALL_H
#define __JA2_ALL_H

#pragma message("GENERATED PCH FOR JA2 PROJECT.")

#include <time.h> 
#include <stdio.h>
#include <stdarg.h>
#include "sgp.h" 
#include "game_loop.h"
#include "image.h"
#include "vobject.h"
#include "vobject_private.h"
#include "vobject_blitters.h"
#include "types.h"
#include "wcheck.h"
#include "render_world.h"
#include "input.h"
#include "screen_ids.h"
#include "overhead.h"
#include "isometric_utils.h"
#include "sysutil.h"
#include "radar_screen.h"
#include "soldier_control.h"
#include "animation_control.h"
#include "animation_data.h"
#include "event_pump.h"
#include "timer_control.h"
#include "render_dirty.h"
#include "sys_globals.h"
#include "interface.h"
#include "soldier ani.h"
#include <wchar.h>
#include <tchar.h>
#include "english.h"
#include "Fileman.h"
#include "messageboxscreen.h"
#include "sgp.h"
#include "fade screen.h"
#include "cursor control.h"
#include "music control.h"
#include "game_init_options_screen.h"
#include "game_settings.h"
#include "utilities.h"
#include "font_control.h"
#include "word_wrap.h"
#include "options_screen.h"
#include "cursors.h"
#include "Screens.h"
#include "init.h"
#include "laptop.h"
#include "map_screen.h"
#include "game_clock.h"
#include "library_database.h"
#include "map_screen_interface.h"
#include "tactical_save.h"
#include "interface_control.h"
#include "text.h"
#include "handle_ui.h"
#include "button_system.h"
#include "lighting.h"
#include "environment.h"
#include "bullets.h"
#include "message.h"
#include <string.h>
#include "overhead_map.h"
#include "strategic_exit_gui.h"
#include "strategic movement.h"
#include "tactical_placement_gui.h"
#include "Air raid.h"
#include "game init.h"
//DEF: Test Code
#ifdef NETWORKED
#include "Networking.h"
#endif
#include "physics.h"
#include "dialogue control.h"
#include "soldier_macros.h"
#include "faces.h"
#include "strategic_map.h"
#include "game_screen.h"
#include "strategic turns.h"
#include "merc_entering.h"
#include "soldier create.h"
#include "soldier_init_list.h"
#include "interface panels.h"
#include "map_information.h"
#include "squads.h"
#include "interface dialogue.h"
#include "auto bandage.h"
#include "meanwhile.h"
#include "strategic ai.h"
#include "sound_control.h"
#include "save_load_screen.h"
#include "game_version.h"
#include "Debug.h"
#include "language_defines.h"
#include "mouse_system.h"
#include "world_def.h"
#include "video.h"
#include "interface items.h"
#include "Maputility.h"
#include "strategic.h"
#include "npc.h"
#include "merc_text_box.h"
#include "tile cache.h"
#include "shade_table_util.h"
#include "exit_grids.h"
#include "summary_info.h" 
#include <time.h>
#include "font.h"
#include "tile_def.h"
#include "edit_screen.h"
#include "ja_screens.h"
#include "animation cache.h"
#include "main_menu_screen.h"
#include "Random.h"
#include "multi_language_graphic_utils.h"
#include "save_load_game.h"
#include "text_input.h"
#include "slider.h"
#include "sound_man.h"
#include "ambient_control.h"
#include "Worlddat.h"
#include "Gap.h"
#include "soldier_profile.h"
#include "keys.h"
#include "finances.h"
#include "History.h"
#include "files.h"
#include "Email.h"
#include "game_events.h"
#include "laptop_save.h"
#include "queen_command.h"
#include "quests.h"
#include "opplist.h"
#include "merc_hiring.h"
#include "Ai.h"
#include "smoke_effects.h"
#include "map_screen_interface_border.h"
#include "map_screen_interface_bottom.h"
#include "map_screen_helicopter.h"
#include "arms_dealer_init.h"
#include "strategic_mines.h"
#include "strategic_town_loyalty.h"
#include "vehicles.h"
#include "merc_contract.h"
#include "strategic_pathing.h"
#include "team_turns.h"
#include "explosion control.h"
#include "creature_spreading.h"
#include "strategic_status.h"
#include "boxing.h"
#include "map_screen_interface_map.h"
#include "lighteffects.h"
#include "ja2_splash.h"
#include "scheduling.h"
#include "_JA25EnglishText.h"
#include "xml.h"

#endif
